version: "3.8"

services:
  webserver:
    build:
      context: .
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      net:
        ipv4_address: 10.5.0.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  git:
    image: gitea/gitea
    container_name: gitea
    restart: always
    networks:
      net:
        ipv4_address: 10.5.0.6
  elasic:
    image: elasticsearch:8.10.2
    container_name: elastic
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host='_local_'
    mem_limit: 25769803776
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      net:
        ipv4_address: 10.5.0.7
volumes:
  webserver:
    driver: local
  git:
    driver: local
  elasic:
    driver: local
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
